--
-- Script was generated by Devart dbForge Studio 2020 for MySQL, Version 9.0.391.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 9/26/2020 6:23:54 PM
-- Server version: 10.4.14
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

--
-- Set default database
--
USE mianimal;

--
-- Drop procedure `spcre_animal`
--
DROP PROCEDURE IF EXISTS spcre_animal;

--
-- Drop procedure `spdel_animal`
--
DROP PROCEDURE IF EXISTS spdel_animal;

--
-- Drop procedure `spsel_animal`
--
DROP PROCEDURE IF EXISTS spsel_animal;

--
-- Drop procedure `spseledit_animal`
--
DROP PROCEDURE IF EXISTS spseledit_animal;

--
-- Drop procedure `spupd_animal`
--
DROP PROCEDURE IF EXISTS spupd_animal;

--
-- Drop table `animal`
--
DROP TABLE IF EXISTS animal;

--
-- Set default database
--
USE mianimal;

--
-- Create table `animal`
--
CREATE TABLE animal (
  id int(11) NOT NULL AUTO_INCREMENT,
  nombre varchar(30) DEFAULT NULL,
  especie varchar(15) DEFAULT NULL,
  genero varchar(10) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 6,
AVG_ROW_LENGTH = 5461,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;

DELIMITER $$

--
-- Create procedure `spupd_animal`
--
CREATE DEFINER = 'root'@'localhost'
PROCEDURE spupd_animal (IN ani_id int, IN ani_nombre varchar(30), IN ani_especie varchar(15), IN ani_genero varchar(10))
BEGIN

  UPDATE animal
  SET nombre = ani_nombre,
      especie = ani_especie,
      genero = ani_genero
  WHERE id = ani_id;

END
$$

--
-- Create procedure `spseledit_animal`
--
CREATE DEFINER = 'root'@'localhost'
PROCEDURE spseledit_animal (IN ani_id int)
BEGIN
  SELECT
    *
  FROM animal
  WHERE id = ani_id;
END
$$

--
-- Create procedure `spsel_animal`
--
CREATE DEFINER = 'root'@'localhost'
PROCEDURE spsel_animal ()
BEGIN
  SELECT
    *
  FROM animal;
END
$$

--
-- Create procedure `spdel_animal`
--
CREATE DEFINER = 'root'@'localhost'
PROCEDURE spdel_animal (IN ani_id int)
BEGIN
  DELETE
    FROM animal
  WHERE id = ani_id;
END
$$

--
-- Create procedure `spcre_animal`
--
CREATE DEFINER = 'root'@'localhost'
PROCEDURE spcre_animal (IN ani_nombre varchar(30), IN ani_especie varchar(15), IN ani_genero varchar(10))
BEGIN
  INSERT INTO animal (nombre, especie, genero)
    VALUES (ani_nombre, ani_especie, ani_genero);
END
$$

DELIMITER ;

-- 
-- Dumping data for table animal
--
INSERT INTO animal VALUES
(1, 'Lucas', 'Perro', 'Macho'),
(2, 'Mini', 'Gato', 'Hembra'),
(3, 'mi perrito', 'Perro', 'Hembra');

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS */;